### ISSUE TITLE
Not work even your demo!

### ISSUE THREAD

**Issue by alimd** [chuckh/polymer-quill#27]
![screen shot 2017-11-22 at 6 20 25 pm](https://user-images.githubusercontent.com/697913/33133426-fd58ab70-cfb1-11e7-8894-aea271e2d53a.png)

Chrome latest version 

![screen shot 2017-11-22 at 6 23 08 pm](https://user-images.githubusercontent.com/697913/33133495-39c5d416-cfb2-11e7-821f-f05851cc4252.png)

load https://raw-dot-custom-elements.appspot.com/chuckh/polymer-quill/v1.2.6/quill/quill.js
`quill is not a valid dependency for v1.2.6 in chuckh/polymer-quill`

**Comment by chuckh** [comment]
The demo does not work on webcomponents.org because they use Shadow DOM instead of Shady DOOM which is required for it to work.  I note in the readme on webcomponents.org to use the links in the readme to see demo.  Such as https://chuckh.github.io/polymer-quill/components/polymer-quill/demo/


![image](https://user-images.githubusercontent.com/19915/35066117-65af69ae-fb84-11e7-8d2e-4c15acca5656.png)
