### ISSUE TITLE
Header styling deletes when use blockquote

### ISSUE THREAD

**Issue by misterzorgy** [chuckh/polymer-quill#8]
Type some words with Heading option, then try to blockquote these words

**Comment by chuckh** [comment]
That is expected behavior. You can't have both.  See below example from Quill Playground.

## Heading 2 selected
![image](https://cloud.githubusercontent.com/assets/19915/22469476/ffc9c4f8-e780-11e6-86c3-ecea55ad8a45.png)

## Then block quote selected
![image](https://cloud.githubusercontent.com/assets/19915/22469516/21bf8110-e781-11e6-897e-0794da02952d.png)
